### ISSUE TITLE
FATAL: no longer a configured node for

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando/lizzy-client#13]
I've executed lizzy-client on Jenkins at 9:59am. Three minutes later, at 10:01am I got following ERROR in logs:

Wating for new stack.. . .FATAL: no longer a configured node for ip-10-144-114-64.z.aws
java.lang.IllegalStateException: no longer a configured node for ip-10-144-114-64.z.aws
	at hudson.model.AbstractBuild$AbstractBuildExecution.getCurrentNode(AbstractBuild.java:456)
	at hudson.model.AbstractBuild$AbstractBuildExecution.reportBrokenChannel(AbstractBuild.java:807)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1744)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)

---
But seems deployment was done, because I see my app "seo-service-staging" successfully deployed on AWS

**Comment by dmitrykrivaltsevich** [comment]
It's Jenkins problem - slaves went offline if master doesn't receive any messages in ~3 minutes
