### ISSUE TITLE
lizzy-client: traffic command fails when multiple versions of same stack are deployed

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando/lizzy-client#22]
Currently we have 3 versions of application deployed by lizzy:

Stack Name | Version | Identifier | Weight %
------------ | ------------- | ------------- | -------------
app | v1 | app-v1 | 100.0
app | v2 | app-v2 | 0.0
app | v3 | app-v3 | 0.0

When I try to route a traffic to the v3 of the app using `lizzy traffic app v3 100` I'm getting following error:

```
Requesting traffic change.. EXCEPTION OCCURRED: 400 Client Error: BAD REQUEST
Traceback (most recent call last):
  File "/usr/local/bin/lizzy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/lizzy_client/cli.py", line 236, in traffic
    lizzy.traffic(stack_id, percentage)
  File "/usr/local/lib/python3.4/dist-packages/lizzy_client/lizzy.py", line 89, in traffic
    request.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST
```

**Comment by dmitrykrivaltsevich** [comment]
This command fails even for 1 stack

**Comment by jmcs** [comment]
Confirmed on the last version.

**Comment by jmcs** [comment]
In the log:

     DEBUG: '100.0' is not a 'int'.
